# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d4af8ee6ea204e9ac35ec4e03f1c9cdf"
name = "Anchor Subscriptions"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders,read_customer_payment_methods,read_customers,read_locales,read_locations,read_orders,read_themes,write_customers,write_metaobject_definitions,write_metaobjects,write_own_subscription_contracts,write_products,write_translations,customer_read_own_subscription_contracts,customer_write_own_subscription_contracts"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
